apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - clusters:
     selector:
       matchLabels:
         regional: "true"
     values:
       type: app
  - clusters:
     selector:
       matchLabels:
         regional: "true"
         singleton: "true"
     values:
       type: migrate
  goTemplate: true
  goTemplateOptions:
  - missingkey=error
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - migrate
          maxUpdate: 100%
        - matchExpressions:
            - key: type
              operator: In
              values:
                - app
  template:
    metadata:
      annotations:
        notifications.argoproj.io/subscribe.on-sync-running.test: ""
        notifications.argoproj.io/subscribe.on-sync-succeeded.test: ""
      labels:
        salesloft-app: guestbook
        type: "{{ .values.type }}"
      name: guestbook-{{ .name }}-{{ .values.type }}
    spec:
      destination:
        namespace: default
        server: '{{ .server }}'
      project: guestbook
      syncPolicy:
        automated: {}
  templatePatch: |
    spec:
      sources:
    {{- if eq .values.type "app" }}
        - repoURL: https://github.com/adrianmoisey/argocd-example-apps
          targetRevision: HEAD
          path: guestbook/

        - repoURL: https://github.com/adrianmoisey/argocd-example-apps
          targetRevision: HEAD
          path: guestbook/{{ .metadata.labels.cell }}

    {{- if index .metadata.labels "singleton" }}
        - repoURL: https://github.com/adrianmoisey/argocd-example-apps
          targetRevision: HEAD
          path: guestbook/singleton
    {{- end }}
    {{- end }}
    {{- if eq .values.type "migrate" }}
        - repoURL: https://github.com/adrianmoisey/argocd-example-apps
          targetRevision: HEAD
          path: guestbook/migrations/
    {{- end }}
